sonar.projectKey=ticket-service
sonar.projectName=Ticket Service - EP2 DOY0101
sonar.projectVersion=0.0.1

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/config/**,**/*Application.java
sonar.cpd.exclusions=**/domain/model/**

sonar.java.source=17
sonar.sourceEncoding=UTF-8
